flowchart
    broadcaster --> ns & pj & xz & sg
    ls -- FF --> cs & jd
    st -- FF --> jh & bj
    hc -- FF --> tn
    xs -- FF --> rr
    pq -- FF --> tl & cs
    rj -- FF --> km & ck
    lb -- FF --> cg
    zz -- FF --> dx & ch
    kk -- FF --> cs & tc
    hr -- FF --> ck & pl
    pj -- FF --> cs & pr
    pr -- FF --> zl & cs
    tl -- FF --> vn & cs
    tc -- FF --> cs & hn
    cs -- Con --> hn & pj & qb & zl
    lv -- FF --> hr
    vn -- FF --> cs & ls
    gg -- FF --> jh & nx
    cr -- FF --> jg & jh
    ch -- FF --> dx
    dx -- Con --> zj & xz & mp & zn & xs & hc
    fl -- FF --> jh & ps
    hn -- FF --> pq
    qp -- FF --> dx & zj
    bp -- FF --> zr
    kl -- FF --> lb
    pl -- FF --> ck & xq
    rm -- FF --> zz & dx
    rz -- FF --> jh & fl
    pm -- FF --> cs & kk
    zl -- FF --> pm
    rk -- FF --> ck & kl
    cg -- FF --> lv & ck
    jg -- FF --> jh
    ck -- Con --> lb & lv & ns & kl & qt
    zr -- FF --> st
    dd -- FF --> dx & qp
    kd -- FF --> rk & ck
    xq -- FF --> rj & ck
    sg -- FF --> rz & jh
    zj -- FF --> hc
    tn -- FF --> dx & xs
    jd -- FF --> cs
    rr -- FF --> rm & dx
    jh -- Con --> ng & bp & zr & sg & bj
    km -- FF --> ck
    ps -- FF --> bp & jh
    zn -- FF --> dd
    bj -- FF --> gg
    nx -- FF --> jh & cr
    xz -- FF --> dx & zn
    ns -- FF --> ck & kd
    subgraph finale
        ng -- Con --> dr
        mp -- Con --> dr
        qt -- Con --> dr
        qb -- Con --> dr
        dr -- Con --> rx
    end
